os: linux
language: php
jobs:
  include:
    - php: '8.0'
      dist: focal
    - php: '8.1'
      dist: jammy
    - php: '8.2'
      dist: jammy
    - php: '8.3'
      dist: jammy

before_script: composer install
script:
   - ./vendor/bin/phpcs
   - ./vendor/bin/phpunit
